apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-storage-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-storage-service
spec:
  ports:
  - port: 3306
  selector:
    app: user-storage-delpoyment
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-storage-delpoyment
spec:
  selector:
    matchLabels:
      app: user-storage-delpoyment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-storage-delpoyment
    spec:
      containers:
      - image: mysql:8.0
        name: user-storage-delpoyment
        env:
        - name: MYSQL_DATABASE
          value: user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
             name: user-service-mysql-password
             key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: user-storage-pv
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m" 
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: user-storage-pv
        persistentVolumeClaim:
          claimName: user-storage-pvc
