apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
  labels:
    app: workout-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: app
          image: lexfuny/workout-service:master
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workout-service
  name: workout-service
spec:
  ports:
    - name: 'http'
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: workout-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workout-service
spec:
  ingressClassName: workout-service-class
  rules:
  - http:
      paths:
      - path: /workout
        pathType: Prefix
        backend:
          service:
            name: workout-service
            port:
              number: 80
